name:                deep-learning-haskell
version:             0.1.0.0
github:              "cleissonbarbosa/deep-learning-haskell"
license:             BSD-3-Clause
author:              "Cleisson Barbosa"
maintainer:          "cleissonbarbosa68@gmail.com"
copyright:           "2025 Cleisson Barbosa"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/cleissonbarbosa/deep-learning-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- massiv
- random
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  deep-learning-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deep-learning-haskell

tests:
  deep-learning-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    other-modules:       
    - Spec.MainSpec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deep-learning-haskell
    - hspec
